/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedYoutubeToQuizRouteImport } from './routes/_authenticated/youtube-to-quiz'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedStudyGuideRouteImport } from './routes/_authenticated/study-guide'
import { Route as AuthenticatedMyQuizzesRouteImport } from './routes/_authenticated/my-quizzes'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedResultsAttemptIdRouteImport } from './routes/_authenticated/results.$attemptId'
import { Route as AuthenticatedQuizQuizIdRouteImport } from './routes/_authenticated/quiz.$quizId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedYoutubeToQuizRoute =
  AuthenticatedYoutubeToQuizRouteImport.update({
    id: '/youtube-to-quiz',
    path: '/youtube-to-quiz',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudyGuideRoute = AuthenticatedStudyGuideRouteImport.update({
  id: '/study-guide',
  path: '/study-guide',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyQuizzesRoute = AuthenticatedMyQuizzesRouteImport.update({
  id: '/my-quizzes',
  path: '/my-quizzes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsAttemptIdRoute =
  AuthenticatedResultsAttemptIdRouteImport.update({
    id: '/results/$attemptId',
    path: '/results/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuizQuizIdRoute = AuthenticatedQuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/my-quizzes': typeof AuthenticatedMyQuizzesRoute
  '/study-guide': typeof AuthenticatedStudyGuideRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/youtube-to-quiz': typeof AuthenticatedYoutubeToQuizRoute
  '/quiz/$quizId': typeof AuthenticatedQuizQuizIdRoute
  '/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/my-quizzes': typeof AuthenticatedMyQuizzesRoute
  '/study-guide': typeof AuthenticatedStudyGuideRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/youtube-to-quiz': typeof AuthenticatedYoutubeToQuizRoute
  '/quiz/$quizId': typeof AuthenticatedQuizQuizIdRoute
  '/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/my-quizzes': typeof AuthenticatedMyQuizzesRoute
  '/_authenticated/study-guide': typeof AuthenticatedStudyGuideRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/youtube-to-quiz': typeof AuthenticatedYoutubeToQuizRoute
  '/_authenticated/quiz/$quizId': typeof AuthenticatedQuizQuizIdRoute
  '/_authenticated/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/history'
    | '/my-quizzes'
    | '/study-guide'
    | '/upload'
    | '/youtube-to-quiz'
    | '/quiz/$quizId'
    | '/results/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/history'
    | '/my-quizzes'
    | '/study-guide'
    | '/upload'
    | '/youtube-to-quiz'
    | '/quiz/$quizId'
    | '/results/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/my-quizzes'
    | '/_authenticated/study-guide'
    | '/_authenticated/upload'
    | '/_authenticated/youtube-to-quiz'
    | '/_authenticated/quiz/$quizId'
    | '/_authenticated/results/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/youtube-to-quiz': {
      id: '/_authenticated/youtube-to-quiz'
      path: '/youtube-to-quiz'
      fullPath: '/youtube-to-quiz'
      preLoaderRoute: typeof AuthenticatedYoutubeToQuizRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/study-guide': {
      id: '/_authenticated/study-guide'
      path: '/study-guide'
      fullPath: '/study-guide'
      preLoaderRoute: typeof AuthenticatedStudyGuideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-quizzes': {
      id: '/_authenticated/my-quizzes'
      path: '/my-quizzes'
      fullPath: '/my-quizzes'
      preLoaderRoute: typeof AuthenticatedMyQuizzesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results/$attemptId': {
      id: '/_authenticated/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/results/$attemptId'
      preLoaderRoute: typeof AuthenticatedResultsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiz/$quizId': {
      id: '/_authenticated/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof AuthenticatedQuizQuizIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedMyQuizzesRoute: typeof AuthenticatedMyQuizzesRoute
  AuthenticatedStudyGuideRoute: typeof AuthenticatedStudyGuideRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedYoutubeToQuizRoute: typeof AuthenticatedYoutubeToQuizRoute
  AuthenticatedQuizQuizIdRoute: typeof AuthenticatedQuizQuizIdRoute
  AuthenticatedResultsAttemptIdRoute: typeof AuthenticatedResultsAttemptIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedMyQuizzesRoute: AuthenticatedMyQuizzesRoute,
  AuthenticatedStudyGuideRoute: AuthenticatedStudyGuideRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedYoutubeToQuizRoute: AuthenticatedYoutubeToQuizRoute,
  AuthenticatedQuizQuizIdRoute: AuthenticatedQuizQuizIdRoute,
  AuthenticatedResultsAttemptIdRoute: AuthenticatedResultsAttemptIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
